// Responsive image attribute helper.
// Variants are generated by `node generate-responsive.mjs`, which also writes
// src/data/image-manifest.json with each original's intrinsic dimensions.

import manifest from '../data/image-manifest.json';

type Meta = { w: number; h: number; v: number[] };
const data = manifest as Record<string, Meta>;

export interface ImgAttrs {
  src: string;
  srcset?: string;
  sizes?: string;
  width?: number;
  height?: number;
}

/**
 * Builds src/srcset/sizes/width/height for a /portfolio-webp/ image.
 * Accepts paths with spaces (raw or %20-encoded) and optional ?v= query.
 * Falls back to a plain src if the file is unknown to the manifest.
 */
export function imgAttrs(src: string, sizes?: string): ImgAttrs {
  const [pathPart, query] = src.split('?');
  const suffix = query ? `?${query}` : '';
  const file = decodeURIComponent(pathPart.split('/').pop() || '');
  const encodedPath = encodeURI(decodeURIComponent(pathPart));
  const meta = data[file];

  if (!meta) return { src: encodedPath + suffix };

  const base = encodedPath.replace(/\.webp$/i, '');
  const entries = meta.v.map((w) => `${base}-${w}w.webp ${w}w`);
  // The original acts as the largest candidate (keep its cache-busting query).
  entries.push(`${encodedPath}${suffix} ${meta.w}w`);

  return {
    src: encodedPath + suffix,
    srcset: entries.join(', '),
    sizes: sizes ?? '100vw',
    width: meta.w,
    height: meta.h,
  };
}
